baseURL = "https://stephenajulu.com"
languageCode = "en-us"
paginate = 12
enableEmoji = true
title = "Stephen Ajulu | Web Developer, Designer & Creator"
# Author
[author]
email = "alunje73@gmail.com"
facebook = "stephenajulu"
name = "Stephen Ajulu"
twitter = "@stephenajulu"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.main]]
name = "Shop"
url = "/store"
weight = 6

# Sitemap Menu
[[menu.sitemap]]
name = "Store"
url = "https://stephenajulu.gumroad.com"
weight = 1
[[menu.sitemap]]
name = "Latest Articles"
url = "https://ajulusthoughts.stephenajulu.com"
weight = 2
[[menu.sitemap]]
name = "Newsletter"
url = "https://stephenajulu.substack.com/subscribe"
weight = 3

[params]
blogPageURL = "blog"
servicesPageURL = "services"
storePageURL = "store"
contactLink = "contact"
copyright = "Â© Stephen Ajulu."
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/alunje73@gmail.com"
logo = "images/site-navigation/logo2.svg"
featureImage = "images/featureImage"
image = "images/featureImage"
images = "images/featureImage"
description = "Hi!ðŸ‘‹ I'm Stephen Ajulu, a Web Developer, Designer & Creator To hire me & learn more, visit my website!"
monetization = "$ilp.uphold.com/GLrwmQrfDeU9"

[params.address]
address = "Nairobi, Kenya."
email = "alunje73@gmail.com"
openingHours = "Contact me between 8am to 5pm, East Africa Time UTC+3"
phone = "+254726024210"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/stephenajulu"
weight = 1
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/stephenajulu"
weight = 2
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/stephenajulu"
weight = 3
[[params.social]]
icon = "fa-github-square"
url = "https://www.github.com/stephenajulu"
weight = 4
